;;; Scheme Recursive Art Contest Entry
;;;
;;; Please do not include your name or personal info in this file.
;;;
;;; Title: <Your title here>
;;;
;;; Description:
;;;   <I run the doctests
;;;    Zero test cases pass. Uhh?
;;;    Time for piazza>
(define (moveset x y)
(pu)
(goto x y)
(pd)
)
(define (letter_e x)
  (seth 270)
  (fd x)
  (rt 90)
  (topleft x)
  (bk x)
  (lt 90)
  (topleft x)
)

(define (topleft x)
  (fd x)
  (rt 90)
  (fd x)
)

(define (letter_oh x)
  (seth 0)
  (circle x)
)
(define (letter_r x)
  (fd x)
  (rt 90)
  (circle (* x 0.5) 180)
  (lt 90)
  (fd x)
  (lt 45)
  (fd (* (expt 2 0.5) x))
)
(define (error z)
  (letter_e z)
  (pu)
  (fd (* z 0.2))
  (rt 90)
  (fd (* z 2))
  (seth 0)
  (pd)
  (letter_r z)
  (lt 135)
  (letter_r z)
  (seth 0)
  (pu)
  (topleft z)
  (fd z)
  (pd)
  (letter_oh z)
  (bk z)
  (letter_r z)
)
(define (column m n z)
  (cond
    ((= m 0) 0)
    (else
      (begin (error z)
             (pu)
             (seth 180)
             (fd (* z 3))
             (seth 270)
             (fd (* z 5.2))
             (pd)
             (column (- m 1) n z)
      )
    )
  )
)
(define (n-col m n z)
  (cond
    ((= n 0) 0)
    (else
      (begin (column m n z)
             (pu)
             (seth 0)
             (fd (* z 3 m))
             (seth 90)
             (fd (* z 7))
             (pd)
             (n-col m (- n 1) z)
      )
    )
  )
)

(define (draw)
  (speed 10)
  ;(moveset (- 700) 100)
  (moveset (- 725) 300)
  (n-col 24 21 10)
  (exitonclick))
(draw)
